---
chore:
  - '.github/**/*'
  - '.gitignore'
documentation:
  - '**/*.md'
github-actions:
  - '.github/workflows/**/*'
needs-review:
  - '**'
  - '.*'
  - '.*/**'
samples:
  - 'SampleNotifications/**/*'
  - 'SampleScripts/**/*'
  - 'SampleYaml/**/*'
