#
# Module manifest for module 'PowerValidatedSolutions'
#
# Generated by: VMware Inc.
#
# Generated on: 30/11/2021
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'PowerValidatedSolutions.psm1'
    
    # Version number of this module.
    ModuleVersion = '1.2.0'
    
    # Supported PSEditions
    # CompatiblePSEditions = @()
    
    # ID used to uniquely identify this module
    GUID = '04e25d59-f231-4a5c-8506-dee433cf99c7'
    
    # Author of this module
    Author = 'Gary Blake, Cloud Infrastructure Business Group (CIBG)'
    CompanyName = 'VMware Inc.'
    
    # Description of the functionality provided by this module
    Description = 'PowerShell Module for VMware Validated Solutions'
    
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'
    
    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''
    
    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''
    
    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()
    
    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = '*'
    
    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = '*'
    
    # Variables to export from this module
    VariablesToExport = '*'
    
    }