#
# Module manifest for module 'PowerValidatedSolutions'
#
# Generated by: VMware Inc.
#
# Generated on: 24/08/2021
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PowerValidatedSolutions.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '08e28c56-f231-4a2c-8906-dee337cf99b4'

# Author of this module
Author = 'Cloud Platform Business Unit (CPBU)'
CompanyName = 'VMware Inc.'

# Description of the functionality provided by this module
Description = 'PowerShell Module for Validated Solutions'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName="VMware.vSphere.SsoAdmin"; ModuleVersion="1.3.1"},@{ModuleName="PowerVCF"; ModuleVersion="2.1.3"},@{ModuleName="VMware.PowerCLI"; ModuleVersion="12.3.0"})

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

}