apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: <!! tanzuNamespaceName !!>
  namespace: <!! tanzuNamespaceName !!>
spec:
  topology:
    controlPlane:
      count: 3
      class: <!! vmClass !!>
      storageClass: <!! storagePolicyName !!>
    workers:
      count: 3
      class: <!! vmClass !!>
      storageClass: <!! storagePolicyName !!>
  distribution:
    version: <!! distributionVersion !!>
  settings:
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]