---
name: Maintainer Access

on:
  pull_request_target:
    types:
      - opened

jobs:
  maintainer-access-check:
    env:
      MAINTAINER_CAN_MODIFY: '${{ github.event.pull_request.maintainer_can_modify }}'
      IN_MAINTAINER_LIST: '${{ contains( secrets.MAINTAINER_LIST, github.actor) }}'
    runs-on: ubuntu-latest
    steps:
      - name: Check Maintainer Edit Permissions
        uses: peter-evans/create-or-update-comment@v3
        if: >-
          ${{ ( env.IN_MAINTAINER_LIST == 'false' ) && (
          env.MAINTAINER_CAN_MODIFY == 'false' ) }}
        with:
          issue-number: '${{ github.event.pull_request.number }}'
          body: >
            Hello, @${{ github.actor }}. :wave: 
            

            Thank you for your contribution! 
            

            At times, maintainers need to make direct edits to pull requests in
            order to help get it ready to be merged. Your current settings do
            not allow maintainers to make such edits. To help facilitate this,
            update your pull request to allow such edits as described in
            GitHub's [Allowing changes to a pull request branch created from a
            fork][1] documentation. 
            

            If you're using a fork owned by an organization, your organization
            may not allow you to change this setting. If that is the case, let
            us know.


            [1]: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
